### ISSUE TITLE
zphysics msvc build failing

### ISSUE THREAD

**Issue by hazeycode** [zig-gamedev/zphysics#2]
On Windows 11:
```
PS C:\Users\rumco\Desktop\zig-gamedev\libs\zphysics> zig build -Dtarget=x86_64-windows-msvc
install
└─ install zphysics-tests
   └─ zig test zphysics-tests Debug x86_64-windows-msvc
      └─ zig build-lib joltc Debug x86_64-windows-msvc failure
error: error: unable to create compilation: LibCStdLibHeaderNotFound
```

Cross compiling from Linux gives many occurrences of the following:
```
error: argument unused during compilation: '-nostdinc++'
/home/chris/projects/zig-gamedev/libs/zphysics/libs/Jolt/Core/Core.h:11:11: error: 'winapifamily.h' file not found
 #include <winapifamily.h>
```

Regression introduced by adoption of Zig packager manager in https://github.com/zig-gamedev/zig-gamedev/commit/1a80092c18ddfeb31ec1252f47f71d344a7fd0ab
